### ISSUE TITLE
Request: Latest Opus RC

### ISSUE THREAD

**Issue by 38github** [enzo1982/superfast#1]
I can understand if you do not wish to add an RC but I would like to take a chance and ask because the latest 1.3rc has quality improvement that I, and hopefully others, appreciate.

**Comment by enzo1982** [comment]
As soon as there is an official Opus 1.3 release, it will be picked up for the next fre:ac release.

If you would like to try 1.3rc with fre:ac now and you are on Windows, I can provide an updated Opus.dll here. Just tell me if you would like a 32 or 64 bit version.

If you are on Linux, you can remove opus.so from the codecs folder. fre:ac will then use your system's libopus.so which you can update to 1.3rc.

**Comment by enzo1982** [comment]
Opus 1.3 is now available in fre:ac release 1.1 alpha 20181201a which also supports SuperFast mode.
