### ISSUE TITLE
standalone binary for server+ffmpeg

### ISSUE THREAD

**Issue by grill02** [enzo1982/superfast#2]
Hello,

 I was very impressed by the speedup mentioned at https://www.freac.org/developer-blog-mainmenu-9/14-freac/257-introducing-superfast-conversions.  Currently I run some video conversions on a server with ffmpeg.  The server does not have a graphical X environment.

I would like to use this multi-threaded codec with ffmpeg if possible, either via a pipe or by splitting the audio and video, encoding the audio with this and video with ffmpeg.

Is this possible?

Failing this, is there a way to run freac in "headless" mode, and pass it commands via the console?

thanks.

**Comment by enzo1982** [comment]
Hi and sorry for answering only now!

There is `freaccmd` for running on the console. It's included in the regular fre:ac builds, so you should use the latest alpha (1.1 alpha 20181201a as of this writing) which also supports SuperFast mode for best results.

Unfortunately, it does not support stdio pipes yet, so you will have to split to separate audio and video files with ffmpeg first and then encode the audio using freaccmd. Not sure if the overhead will still allow a significant speedup...

Run freaccmd with the `--superfast` option, e.g. like this:

`freaccmd -e LAME --superfast <infile> -o <outfile>`

**Comment by grill02** [comment]
thanks for answering.

This works on my local workstation (ubuntu with X graphical environment), but fails on the server 

`ldd ./freaccmd`
gives
`

        libgtk-3.so.0 => not found
        libgdk-3.so.0 => not found
        libpangocairo-1.0.so.0 => not found
        libpango-1.0.so.0 => not found
        libatk-1.0.so.0 => not found
        libXft.so.2 => not found
        libcairo.so.2 => not found
        libgdk_pixbuf-2.0.so.0 => not found
`

These are all X related libraries, which I think might not be needed strictly for command line usage.

**Comment by enzo1982** [comment]
fre:ac and freaccmd use the same libraries internally (freac.so which indirectly depends on GTK+3), so all the UI stuff is still there in freaccmd, just not used.

Thus you'll need to install GTK+3 (which should pull in most of the other dependencies) and libXft in order to run freaccmd. I think I can remove the libXft dependency in a future release though, as that one is used only when building without Cairo support.

**Comment by grill02** [comment]
Indeed, installing gtk3-dev and libxft-dev fixed the missing symbols error.

btw, have you thought of merging your work on the 'superfast' opus and aac codecs into ffmpeg? I would think your improvements would be useful to a lot of people, and ffmpeg is used very widely.

**Comment by enzo1982** [comment]
I would certainly like to see ffmpeg support something like the SuperFast technology. I don't have time to implement it, though. But the sources to the SuperFast codecs are available, so if anyone would like to do this, that would certainly be possible.
